#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz promptinit
promptinit
prompt sorin

PROMPT='[%D{%F} %D{%T}] '${PROMPT}

alias ll='ls -la'
alias gl='git log'
alias gs='git status'
alias gb='git branch'
alias gbd='gb -d'
alias gbD='gb -D'
alias gf='git fetch'
alias gc='git checkout'
alias gcb='gc -b'
alias gcm='gc main'
alias gcmst='gc master'
alias gS='git stash'
alias gSl='gS list'
alias gSp='gS pop'
alias gSd='gS drop'
alias gm='git merge'
alias ga='git add'
alias gC='git commit'
alias gCm='gC -m'
alias gCa='gC --amend'
alias gr='git reset'
alias grh='gr --hard'
alias gp='git pull'
alias gpo='gp origin'
alias gpom='gpo main'
alias gpomst='gpo master'
alias gP='git push'
alias gPo='gP origin'
alias gPoh='gPo HEAD'

alias swnode='nvm install $(cat .node-version) && nvm use $(cat .node-version)'

bindkey -e

export NVM_DIR="${HOME}/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/google-cloud-sdk/path.zsh.inc" ]; then . "${HOME}/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ]; then . "${HOME}/google-cloud-sdk/completion.zsh.inc"; fi

export PATH="/opt/homebrew/opt/mysql-client/bin:${PATH}"

export PYENV_ROOT="${HOME}/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:${PATH}"
eval "$(pyenv init --path)"

export PATH="/opt/homebrew/opt/openjdk/bin:${PATH}"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"
export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
export PATH="${PATH}:${HOME}/Library/Android/sdk/platform-tools"
export CLOUDSDK_PYTHON="${HOME}/.pyenv/shims/python"

# pnpm
export PNPM_HOME="${HOME}/Library/pnpm"
case ":${PATH}:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:${PATH}" ;;
esac
# pnpm end

export EDITOR=vi
eval "$(direnv hook zsh)"

export PATH=${PATH}:${HOME}/.local/bin:${HOME}/.bin
